### ISSUE TITLE
Need to update turret aim call

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/bot-control-android#1]
I'm currently seeing the following logged warning when aiming the turret via the Android interface.

```
ctrl_server.py | call_method | 265 | WARNING | Invalid method: 'gunner.aim_turret'
```

I think some gunner code has changed and it just needs to be pointed to the new method. We need to have this done by Friday, for testing before Saturday's demo.

**Comment by napratin** [comment]
The offending line is [this](https://github.com/IEEERobotics/bot-control-android/blob/master/src/edu/ncsu/ieee/botcontrol/BotControl.java#L192):

``` java
turretCmdObj = makeCallReq("gunner", "aim_turret", new String[] { "yaw", "pitch" }, new Object[] { yaw, pitch });
```

Currently, there is no way to set turret's yaw and pitch at the same time (we have to make two separate calls to `turret.set_yaw` and `turret.set_pitch`). I can change bot-control (this Android interface) to use two calls, but it'll be better to have an atomic update command, either by reintroducing `gunner.aim_turret` (which will simply set turret's pitch and yaw, and bot-control would remain unchanged), or by implementing a similar method in turret, e.g. `turret.set(yaw, pitch)` (in this case, the above line in bot-control will need to be updated accordingly).

Any preferences?

**Comment by dfarrell07** [comment]
Let's just make a `turret.aim` wrapper for `turret.set_pitch` and `turret.set_yaw`. I can knock that out right now.

**Comment by dfarrell07** [comment]
Light wrapper added in 4117de1298059e81f769f0eee6635d8758296ae6.

**Comment by dfarrell07** [comment]
Can you drop the latest APK on Drive when you get a chance?

**Comment by napratin** [comment]
Sure, I will.

**Comment by napratin** [comment]
I've put the APK under Apps/ - let me know if this works.
