### ISSUE TITLE
Outdated IDE

### ISSUE THREAD

**Issue by kvijay1995** [IEEERobotics/bot-control-android#3]
It looks like the IDE used to develop this project (Eclipse with ADT plug in) is going to become outdated soon as Google Android devs have officially said they are stopping support for the Eclipse plug-in at the end of this year.

I think we should migrate to Android studio for development while we are reworking this app for this year. What do you guys think?

**Comment by AhmedSamara** [comment]
Ideally, github repositories are hardware agnostic.
Any files related to the IDE should be included in the .gitignore file,
and generated by the individual developer whenever they import the project
into their dev environment.

**Comment by kvijay1995** [comment]
Ah you're right! I was on the wrong thought process. The thing that tripped me up was the .gitignore file that didn't include Android studio IDE's related files. 

(future reference link) : http://stackoverflow.com/questions/16736856/what-should-be-in-my-gitignore-for-an-android-studio-project
